### ISSUE TITLE
chat page with an artificial intelligence chat bot on website

### ISSUE THREAD

**Issue by theRomanMercury** [qsharp-community/qsharp-community.github.io#21]
Is it possible to add a chat pagea with an artificial intelligence chat bot written in Q # that uses quantum cryptography and quantum machine learning to the website?

**Comment by crazy4pi314** [comment]
This would not be possible to do literally as we would need actual quantum cryptography hardware to generate keys (for a start). We could make a neat simulator where the communications between two parties are encrypted with a simulated QRNG?

I don't know anything about chat bots/AI for chatbots so maybe someone else could comment on that?

**Comment by theRomanMercury** [comment]
I think superdense coding will be useful and a simulator is required.

**Comment by mertall** [comment]
this is a cool idea, I have done some work in chatbots for business support. Though i am not sure what quantum computing could do... Maybe a quantum pre processing model would be advantageous, chatbots usually are costly in their preprocessing bc you need to train them on large corpus of text.

**Comment by theRomanMercury** [comment]
There are many channels with the community. Community correspondences on these channels and books on quantum computing can be used as text.

**Comment by mertall** [comment]
This discussion touches on the one we are having about a search engine, in order to process a large amount of data we need beefy quantum hardware. If you are taking say a 2000 page corpus of text, which I worked on for a tech company, we require special access to hundreds of GPUs. I think your ideas are awesome, though finding a feasible solution is a whole challenge in itself. I love finding solutions... if you have a solid plan of action for some of these ideas, with some milestones and technical objectives I would happy to flush out the details with you on a skype call and maybe we could make something really cool!

**Comment by theRomanMercury** [comment]
Thank you. I'm on the vacation right now, we can meet next week. We can communicate via https://gitter.im/qsharp-community/community during this time.

**Comment by crazy4pi314** [comment]
I think that the technical issues raised here by @mertall are pretty valid. I think that this would be pretty resource intensive, and the main goal of this community is to help real people interact and collaborate such that bot I think would undermine that. I will point folks to the new [Discord bot for running Q# simulations](https://github.com/qsharp-community/qsharp-discord-bot) in chat, which might be a similar fun project :) Closing here for scope, if there is a more concrete plan we can reopen later.

PS all community communications are now on [Discord](https://discord.qsharp.community)🎉

**Comment by mertall** [comment]
How about first comparing NLP models semantic understanding to Quantum NLP and see if it provides accuracy increase on a Q and A model. Or maybe a simpler model. A qualitative evaluation of Quantum vs classical NLP processing to understand Corpus of Texts. QaQvC

Bob Coecke recently published a paper to understand how to develop semantic understanding understanding Quantum NLP.

**Comment by mertall** [comment]
https://github.com/CQCL/lambeq
