### ISSUE TITLE
qsharphub

### ISSUE THREAD

**Issue by theRomanMercury** [qsharp-community/qsharp-community.github.io#22]
Can we add a platform where Q # codes are shared by Q # Community?

**Comment by crazy4pi314** [comment]
All the code for projects from the community can be found here: https://github.com/qsharp-community/. There are some links to this on the webpage to our GitHub org via the GitHub logos, do you have a suggestion for another way to present this?

**Comment by theRomanMercury** [comment]
I think individuals who want to write code with Q # at https://qsharp.community/ can share Q # codes on their profile (user friendly and social).

**Comment by theRomanMercury** [comment]
For each line of running Q # codes, I can issue a special token to the Q # Community produced at Stellar (https://www.stellar.org/).

**Comment by crazy4pi314** [comment]
I think this is an interesting idea, but I don't think that getting crypto/blockchain stuff involved here is on topic. Thanks!
